language: node_js
node_js:
- '0.11'
notifications:
  slack:
    secure: AwdRx2nyYtlrIV1+DntKAcj4uEfAtz/2hR5Is+c9YhhWxs2CvUepV2YaE84HLS4plgniGpwJExeq2Yw2bAtHhhhnkWorieoJPliSXqmsahQ9mUqtZgtucERRifdak5+AjgyFwcU+hnS1dgJF7yRj6tydRtLBqeBEbmIDBQ/75rU=
